---
- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.gitconfig: gitconfig
    ~/.gitignore: gitignore
    ~/.agignore: agignore
    ~/.tmux.conf: tmux.conf
    ~/.tmux: tmux/
    ~/.vim: vim/
    ~/.vimrc: vimrc
    ~/.zsh: zsh/
    ~/.zshrc: zshrc
    ~/.config: config
    ~/.vim/autoload/plug.vim: vim/autoload/vim-plug/plug.vim
    ~/.vim/bundle/lightline.vim/autoload/lightline/colorscheme/base16_eighties.vim: vim/lightline/base16_eighties.vim

- shell:
    -
      - "git submodule update --init --recursive --remote"
      - "Installing/updating submodules"
    -
      - "mkdir -p ~/.config/base16-shell ~/.vim/autoload ~/.vim/bundle/lightline.vim/autoload/lightline/colorscheme"
      - "Checking folder structure exists"
    -
      - "mkdir -p ~/.config/base16-shell"
      - "Checking folder structure exists"
    -
      - "curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
      - "Installing vim-plug"

